import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Analytics } from '@vercel/analytics/react';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
      <meta name="google-site-verification" content="ZGjOew8bW5ICVRGo5_6gA_wRP-o38WwwM3QUhIaCkzk" />
      </head>
      <body className={inter.className}>{children}
      <Analytics />
      </body>
    </html>
  )
}
